steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/flask-app-456705/flaskapp', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/flask-app-456705/flaskapp']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    secretEnv: ['GITHUB_TOKEN']
    args:
      - '-c'
      - |
        gcloud run deploy flaskapp \
          --image gcr.io/flask-app-456705/flaskapp \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars GITHUB_TOKEN=$GITHUB_TOKEN

images:
  - 'gcr.io/flask-app-456705/flaskapp'

secrets:
  - secretEnv:
      GITHUB_TOKEN: projects/flask-app-456705/secrets/github-token/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY
