steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/flask-app-456705/flaskapp', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/flask-app-456705/flaskapp']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'flaskapp',
      '--image', 'gcr.io/flask-app-456705/flaskapp',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8080',
      '--set-secrets', 'GITHUB_TOKEN=github-token:latest'
    ]

images:
  - 'gcr.io/flask-app-456705/flaskapp'

secrets:
  - secretEnv:
      GITHUB_TOKEN: projects/flask-app-456705/secrets/github-token/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY
